version: "3"
services:
  web:
    image: g2i-api
    build: .
    command: "npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
