const commands = {
  GET_ITEM: "GET_ITEM",
  GET_FOLDER: "GET_FOLDER",
  GET_DIRECTORY: "GET_DIRECTORY",
  ADD_ITEM: "ADD_ITEM",
  ADD_FOLDER: "ADD_FOLDER",
  UPDATE_ITEM: "UPDATE_ITEM",
  UPDATE_FOLDER: "UPDATE_FOLDER",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_FOLDER: "REMOVE_FOLDER",
};

module.exports = commands;
